os:
- linux
language: node_js
node_js: stable

install:
- npm install -g npm
- npm install -g hexo
- npm install

before_install:
- openssl aes-256-cbc -K $encrypted_2dad640d34c6_key -iv $encrypted_2dad640d34c6_iv
  -in travis.key.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- git config --global user.name "luozhihua"
- git config --global user.email "mail@luozhihua.com"

script:
- hexo clean
- hexo generate
- hexo deploy
# - rsync -rv --delete -e 'ssh -o stricthostkeychecking=no -p 22' public/ root@luozhihua.com:/web/luozhihua.com

addons:
  ssh_know_hosts:
  - github.com
  - luozhihua.com