os:
- linux
language: node_js
node_js: stable

# 缓存依赖，节省持续集成时间
cache:
  npm: true
  directories:
    - node_modules

before_install:
- openssl aes-256-cbc -K $encrypted_2dad640d34c6_key -iv $encrypted_2dad640d34c6_iv
  -in .travis/travis.key.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- git config --global user.name "luozhihua"
- git config --global user.email "mail@luozhihua.com"
- echo "$host_ip ecdsa-sha2-nistp256 $host_public_key" >> $HOME/.ssh/known_hosts

install:
- npm install -g npm
- npm install -g hexo
- rm -rvf ./node_modules/swig
- npm install

before_script:
  - echo -e "Host luozhihua.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

script:
- hexo clean
- hexo generate
- hexo deploy
# - rsync -rv --delete -e 'ssh -o stricthostkeychecking=no -p 22' public/ root@luozhihua.com:/web/luozhihua.com

addons:
  ssh_know_hosts:
  - github.com
  - luozhihua.com
  - 47.52.134.25:22