# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 山外斜阳
subtitle:
description:
author: Colin
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://luozhihua.com
root: /
permalink: :title.html
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: cat
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: true
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: true

# Category & Tag
default_category: uncategorized
category_map:
  新闻: news
  News: news
  活动: activity
  Activity: activity
  技术: tech
  Tech: tech
  Technology: tech
  笔记: note
  Note: note
  Notes: note
  走四方: trip
  产品: prod
  Product: prod
  Products: prod
  项目: proj
  Project: proj
  Projects: proj

tag_map:
  新闻: news
  News: news
  技术: tech
  Tech: tech
  活动: activity
  AppLink: applink
  Applink: applink
  appLink: applink
  DeepLink: deeplink
  Deeplink: deeplink
  deepLink: deeplink
  深度链接: deeplink
  通用链接: universal-link
  universalLink: universal-link
  苹果: apple
  Apple: apple
  谷歌: google
  Google: google
  安卓: android
  Android: android
  兼容性: compatibility
  iOS: ios
  iOs: ios
  UC: uc
  UC浏览器: uc
  浏览器: browser
  Browser: browser
  Chrome: chrome
  Firefox: firefox
  火狐: firefox
  火狐浏览器: firefox
  搜狗浏览器: sougou
  搜狗: sougou
  QQ浏览器: qq-browser
  百度浏览器: baidu-browser
  360浏览器: 360-browser
  海豚浏览器: dolphin-browser
  猎豹浏览器: liebao-browser
  遨游浏览器: aoyou-browser
  Safari: safari
  Weixin: weixin
  Wechat: weixin
  微信: weixin
  微博: weibo
  新浪微博: weibo
  Weibo: weibo

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
#theme: landscape
theme: hueman

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: rsync
  host: luozhihua.com
  user: root
  root: /web/luozhihua.com
  port: 22
  delete: false
  verbose: true
  ignore_errors: false

  # type: rsync
  # host: luozhihua.com
  # user: root
  # root: /web/deeplinks.in
  # port: 22
  # delete: false
  # verbose: true
  # ignore_errors: false

  # type: git
  # repo: git@github.com:deeplinks-in/deeplinks-in.github.io.git
  # branch: master

rss: /atom.xml #rss地址  默认即可

# Minifier
# Note: can wrap a chunk in:
# <!-- htmlmin:ignore -->
# to have the minifier ignore a section
html_minifier:
  exclude:
  removeComments: true
  removeCommentsFromCDATA: true
  removeCDATASectionsFromCDATA: true
  collapseWhitespace: true
  conservativeCollapse: true
  preserveLineBreaks: true
  collapseBooleanAttributes: true
  removeAttributeQuotes: false
  removeRedundantAttributes: true
  preventAttributesEscaping: false
  useShortDoctype: false
  removeEmptyAttributes: true
  removeScriptTypeAttributes: false
  removeStyleLinkTypeAttributes: false
  removeOptionalTags: false
  removeIgnored: true
  removeEmptyElements: false # This appears to break if set to true
  lint: false
  keepClosingSlash: false
  caseSensitive: false
  minifyJS: true
  minifyCSS: true
  minifyURLs: false

  #ignoreCustomComments
  #processScripts
  #maxLineLength
  #customAttrAssign
  #customAttrSurround
  #customAttrCollapse
  #quoteCharacter

#
sitemap:
    path: sitemap.xml

feed:
  type: rss2
  path: rss2.xml
  limit: 20
  hub:

#七牛云存储设置
##offline       是否离线. 离线状态将使用本地地址渲染
##sync          是否同步
##bucket        空间名称.
##access_key    上传密钥AccessKey
##secret_key    上传密钥SecretKey
##secret_file   秘钥文件路径，可以将上述两个属性配置到文件内，防止泄露，json格式。绝对路径相对路径均可
##dirPrefix     上传的资源子目录前缀.如设置，需与urlPrefix同步
##urlPrefix     外链前缀.
##up_host      上传服务器路径,如选择华北区域的话配置为http://up-z1.qiniu.com
##local_dir     本地目录.
##update_exist  是否更新已经上传过的文件(仅文件大小不同或在上次上传后进行更新的才会重新上传)
##image/js/css  子参数folder为不同静态资源种类的目录名称，一般不需要改动
##image.extend  这是个特殊参数，用于生成缩略图或加水印等操作。具体请参考http://developer.qiniu.com/docs/v6/api/reference/fop/image/
##              可使用基本图片处理、高级图片处理、图片水印处理这3个接口。例如 ?imageView2/2/w/500 即生成宽度最多500px的缩略图
qiniu:
  offline: false
  sync: true
  bucket: luozhihuablog
  secret_file: "/Users/colin/qiniu.json"
  # access_key: Dt7f4cSL386EkJ4MTjlQTiZz_gO43owVHHmPz6Xd
  # secret_key: C4R5R5t2_yOMkPK1XxslfK-kNNOSUV7jlHig0wNW
  dirPrefix: static
  urlPrefix: http://oezzzs8eh.bkt.clouddn.com/static
  up_host: http://up.qiniu.com
  local_dir: static
  update_exist: false
  ignoring_log: false
  ignoring_files:
    - '**/.*'
    - '**/.picasaoriginals/**'
    - '**/.picasaoriginals/.*'
    - "**/*.tmp"

  image:
    folder: images
    extend:
  js:
    folder: js
  css:
    folder: css

# 移除未使用的CSS
uncss:
  enable   : true
  ignore   : "#added_at_runtime"
  # media    : (min-width: 700px) handheld and (orientation: landscape)
  priority : 10
  timeout  : 1000
  # uncssrc  : .uncssrc