# Menus
menu:
    Home: /
    # Delete this row if you don't want categories in your header nav bar
    Categories:
    # About: /about/index.html

# Customize
customize:
    logo:
        width: 400
        height: 160
        url: /imgs/logo.png
    theme_color: '#FC5213'

    # monokai, monokai-sublime, github, googlecode, docco, foundation, tomorrow-night, xcode
    highlight: monokai-sublime
    sidebar: left # sidebar position, options: left, right
    thumbnail: true # enable posts thumbnail, options: true, false
    favicon: /imgs/favicon.ico # path to favicon
    social_links: # for more icons, please see http://fontawesome.io/icons/#brand
        twitter: https://twitter.com/colinluo
        facebook: https://www.facebook.com/colin.luo.1988
        google-plus: https://plus.google.com/u/0/110094857613114167967
        github: https://github.com/luozhihua/
        weibo: http://weibo.com/luozhihua
        rss: /rss2.xml

# Widgets
widgets:
    - recent_posts
    # - category
    - archive
    # - tag
    - tagcloud
    - links

# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false

# Comment
comment:
    #disqus: luozhihua # enter disqus shortname here
    #duoshuo: luozhihua # enter duoshuo shortname here
    #youyan: 1571736 # enter youyan uid here
    changyan:
        appid: cyteu6NaD
        appkey: prod_963bc81e11a3607fdeb53764a3a40a9b

# Share
share: addtoany # options: jiathis, bdshare, addtoany, default

# Plugins
plugins:
    lightgallery: true # options: true, false
    google_analytics: UA-15015199-4 # enter the tracking ID for your Google Analytics
    baidu_analytics: # enter Baidu Analytics hash key
    piwik_analytics:
        host: piwik.luozhihua.com # enter Piwik Host
        siteid: 2 # enter Piwik Site ID

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins: 100004103689176
        twitter_id: colinluo
        google_plus: https://plus.google.com/u/0/110094857613114167967
    links:
        Hexo: http://hexo.io
